[package]

name = "librustpiyin"
version = "0.0.1"
authors = [ "Allan Simon <allan.simon@supinfo.com>" ]

[lib]
name = "pinyinengine"
path = "src/lib.rs"
crate-type = ["dylib"]

[[bin]]

name = "read"

[[bin]]

name = "bench_read_dump_db"
